#!/bin/bash

USER_NAME=$1

#cp bashrc ~/.bashrc
#cp vimrc ~/.vimrc
#cp -R screenlayout ~/.screenlayout

cp -R userhome/* /home/$USER_NAME/

#cp startp /usr/bin
#cp s /usr/bin
#cp p /usr/bin

cp -R usr/* /usr/

ip addr

echo
echo "!--- switch eth0 with whatever your device name is ---!"
echo

sleep 5

vim network.service

cp network.service /etc/systemd/system/multi-user.target.wants/

systemctl daemon-reload
systemctl start network.service

echo
echo "!--- if ping fails network setup failed! ---!"
echo

sleep 2

ping google.com

exit

echo
echo "!--- Now going to install a few programs ---!"
echo

sleep 2

##pacman --noconfirm -S vim
#pacman --noconfirm -S wget
#pacman --noconfirm -S openbox
##pacman --noconfirm -S xorg
#pacman --noconfirm -S xorg-xinit
#pacman --noconfirm -S xfce4
##pacman --noconfirm -S git
##pacman --noconfirm -S go
#pacman --noconfirm -S mpc
#pacman --noconfirm -S ncmpcpp
#pacman --noconfirm -S alsa-utils
#pacman --noconfirm -S htop
#pacman --noconfirm -S dwb
#pacman --noconfirm -S gst-plugins-good
##pacman --noconfirm -S dmenu
##pacman --noconfirm -S figlet
#pacman --noconfirm -S flashplugin
#pacman --noconfirm -S transmission-gtk
##pacman --noconfirm -S scrot
##pacman --noconfirm -S gimp

echo
echo "!--- Now going to set up user $USER_NAME ---!"
echo

sleep 2

#useradd -m -s /bin/bash $USER_NAME
#passwd $USER_NAME

echo "!--- Now going to configure programs ---!"

sleep 2

mkdir /$USER_NAME/.config
cp -R openbox /$USER_NAME/.config
cp xsession /$USER_NAME/.xsession
openbox --reconfigure

cp -R irssi /$USER_NAME/.irssi

cp -R ncmpcpp /$USER_NAME/.ncmpcpp

cp bashrc /$USER_NAME/.bashrc
cp vimrc /$USER_NAME/.vimrc
cp xinitrc /$USER_NAME/.xinitrc
#cp -R screenlayout /$USER_NAME/.screenlayout

# make suer user owns all their files
#chown -R $USER_NAME /$USER_NAME

echo
echo "!--- Done ---!"
echo

### optional section ###
#
#pacman --noconfirm -S mpd
#
## Virtualbox section
#
#pacman --noconfirm -S virtualbox
#depmod -a
#modprobe vboxdrv
#modprobe vboxpci
#cp virtualbox.conf /etc/modules-load.d/virtualbox.conf
#
#pacman --noconfirm -S qt4
#
##pacman --noconfirm -S virtualbox-guest-iso
#
## make default user
#
#
###
