#!/bin/bash

USER_NAME=$1

cp bashrc ~/.bashrc
cp vimrc ~/.vimrc
cp -R screenlayout ~/.screenlayout

cp startp /usr/bin
cp s /usr/bin

ip addr

echo
echo "!--- switch eth0 with whatever your device name is ---!"
echo

sleep 5

vim network.service

cp network.service /etc/systemd/system/multi-user.target.wants/

systemctl daemon-reload
systemctl start network.service

echo
echo "!--- if ping fails network setup failed! ---!"
echo

sleep 2

ping google.com

echo
echo "!--- Now going to install a few programs ---!"
echo

sleep 2

#pacman --noconfirm -S vim
#pacman --noconfirm -S wget
#pacman --noconfirm -S openbox
#pacman --noconfirm -S xorg
#pacman --noconfirm -S xorg-xinit
#pacman --noconfirm -S xfce4
#pacman --noconfirm -S git
#pacman --noconfirm -S go
#pacman --noconfirm -S mpc
#pacman --noconfirm -S ncmpcpp
#pacman --noconfirm -S htop
#pacman --noconfirm -S surf
#pacman --noconfirm -S dmenu
#pacman --noconfirm -S figlet
#pacman --noconfirm -S flashplugin

echo
echo "!--- Now going to set up user $USER_NAME ---!"
echo

sleep 2

useradd -m -s /bin/bash $USER_NAME
passwd $USER_NAME

echo "!--- Now going to configure programs ---!"

sleep 2

mkdir /home/$USER_NAME/.config
cp -R openbox /home/$USER_NAME/.config
cp xsession /home/$USER_NAME/.xsession
openbox --reconfigure

cp -R irssi /home/$USER_NAME/.irssi



cp bashrc /home/$USER_NAME/.bashrc
cp vimrc /home/$USER_NAME/.vimrc
cp xinitrc /home/$USER_NAME/.xinitrc
cp -R screenlayout /home/$USER_NAME/.screenlayout

chown -R $USER_NAME /home/$USER_NAME

echo
echo "!--- Done ---!"
echo

### optional section ###
#
#pacman --noconfirm -S mpd
#
## Virtualbox section
#
#pacman --noconfirm -S virtualbox
#
## make default user
#
#
###
